# .github/workflows/ci.yml
name: CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.x'  # or your preferred version

      - name: Install dependencies
        run: npm ci

      - name: Show migrations present (debug)
        run: |
          echo "HEAD $(git rev-parse --short HEAD)"
          echo "Listing src/migrations (if any):"
          ls -la src/migrations || true
          echo "Searching for enum name references:"
          grep -R "enum_pages_blocks_call_to_action_style" -n src || true

      - name: Run migrations on Neon
        env:
          NODE_ENV: production
          PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
        run: |
          echo "Using DB: $DATABASE_URI" | sed 's/:.*@/:****@/'
          npm run payload migrate --yes

      - name: Run Jest tests with coverage
        run: npm run test:coverage

      - name: Publish JSON snapshots to R2
        env: 
          NODE_ENV: production
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
          NEON_DATABASE_URI: ${{ secrets.NEON_DATABASE_URI }}
          CLOUDFLARE_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
          CLOUDFLARE_ACCT_ID: ${{ secrets.CLOUDFLARE_ACCT_ID }}
          CLOUDFLARE_AUTH_TOKEN: ${{ secrets.CLOUDFLARE_AUTH_TOKEN }}
          CLOUDFLARE_ENDPOINT: ${{ secrets.CLOUDFLARE_ENDPOINT }}
          CLOUDFLARE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
          PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
          R2_SNAPSHOTS_BUCKET: ${{ secrets.R2_SNAPSHOTS_BUCKET }}
        run: npm run collection-snap

      # - name: Run Cypress tests
      #   run: npm run cy:run

      # Optional: Merge coverage reports from both Jest and Cypress if needed
      # - name: Merge Coverage Reports
      #   run: npm run merge:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          # files: ./coverage/lcov.info  # adjust path if using merged coverage
          token: ${{ secrets.CODECOV_TOKEN }}  # set this in your repository secrets if needed
          slug: abeciana1/portfolio-website
